### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by SunggooJung** [LTU-RAI/unity_Spot#4]
```
    from Bezier import BezierGait
ModuleNotFoundError: No module named 'Bezier'

```
I tried to change shebang also but not effected.

**Comment by Astrabrat** [comment]
Please try to clone the "spot_simualtion" branch in the git repo and replace the current installation of spot_simulation from SoftServe in the catkin workspace and build.

**Comment by SunggooJung** [comment]
```
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
```
It works, close this issue,
Thanks!
